sudo: required

services:
  - docker

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

before_install:
  - pip install poetry
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_TOKEN" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  - poetry install

script:
  - poetry run flake8 twitch_radio tests
  - poetry run mypy twitch_radio tests
  - poetry run pytest tests
  - docker build -t tomasfarias/twitch-radio .
  - docker tag tomasfarias/twitch-radio registry.heroku.com/$HEROKU_APP_NAME/twitch-radio

deploy:
  provider: script
  script:
    - docker push tomasfarias/twitch-radio
    - docker push registry.heroku.com/$HEROKU_APP_NAME/twitch-radio
    - heroku container:release twitch-radio --app $HEROKU_APP_NAME
  on:
    branch: master
